# Building wheels for Linux and MacOS platforms
language: python

env:
  global:
    - TWINE_USERNAME=bmatthieu3
    - DOCKER_IMAGE_LINUX_32=daald/ubuntu32:xenial
    - DOCKER_CONTAINER_LINUX_32=linux32_container

# Define the order of the stages
stages:
  - test
  # Stage reponsible for building and publishing the wheels
  # to PyPI. Architecture supported:
  # - manylinux1_i686 py2.7/py3.4->3.7
  # - manylinux1_x86_64 py2.7/py3.4->3.7
  # - osx py2.7/py3.4->3.7
  - deploy

jobs:
  include:
    #### TESTING STAGE ####
    - stage: test
      # - linux
      name: "Python2 linux_x86"
      os: linux
      env:
        - PIP=pip2
        - PYTHON=python2
      script: ./travis/testing.sh
    - name: "Python3 linux_x86"
      os: linux
      env:
        - PIP=pip
        - PYTHON=python
      script: ./travis/testing.sh
      # - linux 32bit
    - name: "Python2 linux_i686"
      os: linux
      services:
        - docker
      before_install:
        - docker pull "${DOCKER_IMAGE_LINUX_32}"
        - >
          docker run
          --volume ${PWD}:/mnt/cdshealpix
          --name "${DOCKER_CONTAINER_LINUX_32}"
          --rm
          --interactive
          --tty
          --detach
          "${DOCKER_IMAGE_LINUX_32}"
      before_script:
      script:
        - >
          docker exec 
          --interactive
          --tty
          "${DOCKER_CONTAINER_LINUX_32}"
          sh -c "cd /mnt/cdshealpix && ./travis/testing_py2_ubuntu_32.sh"
    - name: "Python3 linux_i686"
      os: linux
      services:
        - docker
      before_install:
        - docker pull "${DOCKER_IMAGE_LINUX_32}"
        - >
          docker run
          --volume ${PWD}:/mnt/cdshealpix
          --name "${DOCKER_CONTAINER_LINUX_32}"
          --rm
          --interactive
          --tty
          --detach
          "${DOCKER_IMAGE_LINUX_32}"
      before_script:
      script:
        - >
          docker exec 
          --interactive
          --tty
          "${DOCKER_CONTAINER_LINUX_32}"
          sh -c "cd /mnt/cdshealpix && ./travis/testing_py3_ubuntu_32.sh"
      # - MacOS
    - name: "Python2 OSX"
      os: osx
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
      script: ./travis/testing.sh
    - name: "Python3 OSX"
      os: osx
      language: generic
      env:
        - PIP=pip
        - PYTHON=python
      script: ./travis/testing.sh
    - name: "Build docs"
      os: linux
      env:
        - PIP=pip
        - PYTHON=python
      script: ./travis/build_docs.sh
    #### DEPLOYING STAGE ####
    - stage: deploy
      name: "manylinux1_x86_64"
      # Job generating the wheels for Linux 32-bit platforms
      os: linux
      sudo: required
      env:
        - CIBW_SKIP=*manylinux1_i686*
        - PIP=pip
        - PYTHON=python
      services:
        # We use docker for generating the wheels for Linux.
        - docker
      script: ./travis/deploy.sh
    - name: "manylinux1_i686"
      # Job generating the wheels for Linux 64-bit platforms
      os: linux
      sudo: required
      env:
        - CIBW_SKIP=*manylinux1_x86_64*
        - PIP=pip
        - PYTHON=python
      services:
        # We use docker for generating the wheels for Linux.
        - docker
      script: ./travis/deploy.sh
    - name: "MacOS"
      os: osx
      sudo: required
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
      script: ./travis/deploy.sh
