# Building wheels for Linux and MacOS platforms
language: python

env:
  global:
    - TWINE_USERNAME=bmatthieu3

# Define the order of the stages
stages:
  - test
  # Stage reponsible for building and publishing the wheels
  # to PyPI. Architecture supported:
  # - manylinux1_i686 py2.7/py3.4->3.7
  # - manylinux1_x86_64 py2.7/py3.4->3.7
  # - osx py2.7/py3.4->3.7
  - deploy

jobs:
  include:
    #### TESTING STAGE ####
    - stage: test
      # - linux
      name: "Python2 linux_x86"
      os: linux
      env:
        - PIP=pip2
        - PYTHON=python2
      script: ./testing.sh
    - name: "Python3 linux_x86"
      os: linux
      env:
        - PIP=pip
        - PYTHON=python
      script: ./testing.sh
      # - manylinux 32bit
    - name: "Python2 linux_32"
      os: linux
      services:
        - docker
      before_install:
        - docker pull daald/ubuntu32:xenial
      before_script:
      script:
        - >
          docker run
          --interactive
          --volume "${PWD}"
          daald/ubuntu32:xenial
          ./testing_py2_ubuntu32.sh
    - name: "Python3 linux_32"
      os: linux
      services:
        - docker
      before_install:
        - docker pull daald/ubuntu32:xenial
      before_script:
      script:
        - >
          docker run
          --interactive
          --volume "${PWD}"
          daald/ubuntu32:xenial
          ./testing_py3_ubuntu32.sh
      # - MacOS
    - name: "Python2 OSX"
      os: osx
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
      script: ./testing.sh
    - name: "Python3 OSX"
      os: osx
      language: generic
      env:
        - PIP=pip
        - PYTHON=python
      script: ./testing.sh
    #### DEPLOYING STAGE ####
    - stage: deploy
      name: "manylinux1_x86_64"
      # Job generating the wheels for Linux 32-bit platforms
      os: linux
      sudo: required
      env:
        - CIBW_SKIP=*manylinux1_i686*
        - PIP=pip
        - PYTHON=python
      services:
        # We use docker for generating the wheels for Linux.
        - docker
      script: ./deploy.sh
    - name: "manylinux1_i686"
      # Job generating the wheels for Linux 64-bit platforms
      os: linux
      sudo: required
      env:
        - CIBW_SKIP=*manylinux1_x86_64*
        - PIP=pip
        - PYTHON=python
      services:
        # We use docker for generating the wheels for Linux.
        - docker
      script: ./deploy.sh
    - name: "MacOS"
      os: osx
      sudo: required
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
      script: ./deploy.sh