# The starting point of this script are the links provided on the maturing doc:
# * https://github.com/nanoporetech/fast-ctc-decode/blob/b226ea0f2b2f4f474eff47349703d57d2ea4801b/.github/workflows/publish.yml
# * https://github.com/konstin/complex-manylinux-maturin-docker/blob/main/.github/workflows/build.yml

name: publish-cdshealpix-wheels-aarch64

# Exec only if a tag starting by 'v' is pushed
# see: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
on: [push]

# Jobs run in parallel, see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs 
# Github hosted runner are: see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
jobs:
  
  # Comming in large parts from @odidev in MOCPy pull request
  build-aarch64-wheels:
    runs-on: ubuntu-latest
    env:
      MATURIN_USERNAME: ${{ secrets.PYPI_USERNAME_FXP }}
      MATURIN_PASSWORD: ${{ secrets.PYPI_PASSWORD_FXP }}
      img: quay.io/pypa/manylinux2014_aarch64
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: "Set up QEMU"
       id: qemu
       uses: docker/setup-qemu-action@v1
     - name: Install dependencies
       run: |
         docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
         -e MATURIN_USERNAME=${{ env.MATURIN_USERNAME }} \
         -e MATURIN_PASSWORD=${{ env.MATURIN_PASSWORD}} \
         ${{ env.img }} \
         bash -exc 'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
           source $HOME/.cargo/env && \
           for PYBIN in /opt/python/cp3[678910]*/bin; do
             echo "Loop on PYBIN: $PYBIN"
             "${PYBIN}/pip" install maturin
             "${PYBIN}/maturin" publish -i "${PYBIN}/python" --skip-existing --no-sdist --manylinux 2014 --username "$MATURIN_USERNAME"
           done'


